--- #YAML:1.0
name:                Netscape-Bookmarks
version:             2.2_02
abstract:            Parse or create Mozilla bookmark files
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    HTML::Entities:                0
    HTML::Parser:                  3.26
    HTTP::SimpleLinkChecker:       0
    Test::File:                    0
    Test::More:                    0
    Text::Diff:                    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
