# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Netscape-Bookmarks
version:      1.7
version_from: lib/Bookmarks.pm
installdirs:  site
requires:
    HTML::Entities:                0
    HTML::Parser:                  0
    URI::URL:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
